var things = [
  {
    "Characteristics": [],
    "thingId": 2,
    "code": "S/L BLOCK",
    "name": "S/L BLOCK",
    "status": "active",
    "description": "SHORT / LONG BLOCK",
    "parentThingId": 207,
    "thingLvlDescription": "Área",
    "thingLvl": 2,
    "thingType": null,
    "physicalConn": "S/L BLOCK",
    "position": 1
  },
  {
    "Characteristics": [],
    "thingId": 3,
    "code": "OVAL",
    "name": "OVAL",
    "status": "active",
    "description": "OVAL",
    "parentThingId": 207,
    "thingLvlDescription": "Área",
    "thingLvl": 2,
    "thingType": null,
    "physicalConn": "OVAL",
    "position": 2
  },
  {
    "Characteristics": [],
    "thingId": 4,
    "code": "UPFIT",
    "name": "ACABAMENTO",
    "status": "active",
    "description": "ACABAMENTO",
    "parentThingId": 207,
    "thingLvlDescription": "Área",
    "thingLvl": 2,
    "thingType": null,
    "physicalConn": "ACABAMENTO",
    "position": 2
  },
  {
    "Characteristics": [],
    "thingId": 6,
    "code": "10125",
    "name": "10125 - Picking Light Esquerdo",
    "status": "active",
    "description": "10125 - Picking Light Esquerdo",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "10125",
    "position": 10125
  },
  {
    "Characteristics": [],
    "thingId": 7,
    "code": "10145",
    "name": "10145 - Torque Bujões/Conectores",
    "status": "active",
    "description": "10145 - Torque Bujões/Conectores",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "10145",
    "position": 10145
  },
  {
    "Characteristics": [],
    "thingId": 8,
    "code": "10257",
    "name": "10257 - Retrabalho",
    "status": "active",
    "description": "10257 - Retrabalho",
    "parentThingId": 209,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "10257",
    "position": 10257
  },
  {
    "Characteristics": [],
    "thingId": 9,
    "code": "10400",
    "name": "10400 - Soltar Capas Mancal / Mtg Bronzinas Capas",
    "status": "active",
    "description": "10400 - Soltar Capas Mancal / Mtg Bronzinas Capas",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "10400",
    "position": 10400
  },
  {
    "Characteristics": [],
    "thingId": 10,
    "code": "10500",
    "name": "10500 - Mtg Virabrequim",
    "status": "active",
    "description": "10500 - Mtg Virabrequim",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "10500",
    "position": 10500
  },
  {
    "Characteristics": [],
    "thingId": 11,
    "code": "10600",
    "name": "10600 - Torque dos Mancais",
    "status": "active",
    "description": "10600 - Torque dos Mancais",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "10600",
    "position": 10600
  },
  {
    "Characteristics": [],
    "thingId": 12,
    "code": "10650",
    "name": "10650 - Mesa Giratória",
    "status": "active",
    "description": "10650 - Mesa Giratória",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "10650",
    "position": 10650
  },
  {
    "Characteristics": [],
    "thingId": 13,
    "code": "10657",
    "name": "10657 - Retrabalho",
    "status": "active",
    "description": "10657 - Retrabalho",
    "parentThingId": 209,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "10657",
    "position": 10657
  },
  {
    "Characteristics": [],
    "thingId": 14,
    "code": "10800",
    "name": "10800 - Bore Coding",
    "status": "active",
    "description": "10800 - Bore Coding",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "10800",
    "position": 10800
  },
  {
    "Characteristics": [],
    "thingId": 15,
    "code": "10900",
    "name": "10900 - Posicionamento Camisas no Bloco",
    "status": "active",
    "description": "10900 - Posicionamento Camisas no Bloco",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "10900",
    "position": 10900
  },
  {
    "Characteristics": [],
    "thingId": 16,
    "code": "11300",
    "name": "11300 - Engr. do Comando / Selo / Tpa Tras",
    "status": "active",
    "description": "11300 - Engr. do Comando / Selo / Tpa Tras",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "11300",
    "position": 11300
  },
  {
    "Characteristics": [],
    "thingId": 17,
    "code": "11400",
    "name": "11400 - Mtg dos Pistões",
    "status": "active",
    "description": "11400 - Mtg dos Pistões",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "11400",
    "position": 11400
  },
  {
    "Characteristics": [],
    "thingId": 18,
    "code": "11505",
    "name": "11505 - Torque da Capa da Biela",
    "status": "active",
    "description": "11505 - Torque da Capa da Biela",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "11505",
    "position": 11505
  },
  {
    "Characteristics": [],
    "thingId": 19,
    "code": "11600",
    "name": "11600 - Mesa Giratória",
    "status": "active",
    "description": "11600 - Mesa Giratória",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "11600",
    "position": 11600
  },
  {
    "Characteristics": [],
    "thingId": 20,
    "code": "11757",
    "name": "11757 - Retrabalho",
    "status": "active",
    "description": "11757 - Retrabalho",
    "parentThingId": 209,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "11757",
    "position": 11757
  },
  {
    "Characteristics": [],
    "thingId": 21,
    "code": "11800",
    "name": "11800 - Medição da Protusão e Classif Juntas",
    "status": "active",
    "description": "11800 - Medição da Protusão e Classif Juntas",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "11800",
    "position": 11800
  },
  {
    "Characteristics": [],
    "thingId": 22,
    "code": "11920",
    "name": "11920 - Mtg Prisioneiro / Sensor Ponto / Tpa Tucho / Dreno Comb",
    "status": "active",
    "description": "11920 - Mtg Prisioneiro / Sensor Ponto / Tpa Tucho / Dreno Comb",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "11920",
    "position": 11920
  },
  {
    "Characteristics": [],
    "thingId": 23,
    "code": "12020",
    "name": "12020 - Mtg Bba Comb / Compressor",
    "status": "active",
    "description": "12020 - Mtg Bba Comb / Compressor",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "12020",
    "position": 12020
  },
  {
    "Characteristics": [],
    "thingId": 24,
    "code": "12100",
    "name": "12100 - Mtg Compressor / Adap Hidr",
    "status": "active",
    "description": "12100 - Mtg Compressor / Adap Hidr",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "12100",
    "position": 12100
  },
  {
    "Characteristics": [],
    "thingId": 25,
    "code": "12250",
    "name": "12250 - Preparação do Cabeçote para Torque",
    "status": "active",
    "description": "12250 - Preparação do Cabeçote para Torque",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "12250",
    "position": 12250
  },
  {
    "Characteristics": [],
    "thingId": 26,
    "code": "12420",
    "name": "12420 - Máquina Torque Cabeçote HMS",
    "status": "active",
    "description": "12420 - Máquina Torque Cabeçote HMS",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "12420",
    "position": 12420
  },
  {
    "Characteristics": [],
    "thingId": 27,
    "code": "12450",
    "name": "12450 - Mesa Giratória",
    "status": "active",
    "description": "12450 - Mesa Giratória",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "12450",
    "position": 12450
  },
  {
    "Characteristics": [],
    "thingId": 28,
    "code": "12457",
    "name": "12457 - Retrabalho Torque Cabeçote",
    "status": "active",
    "description": "12457 - Retrabalho Torque Cabeçote",
    "parentThingId": 209,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "12457",
    "position": 12457
  },
  {
    "Characteristics": [],
    "thingId": 29,
    "code": "12530",
    "name": "12530 - Torque Cabeçote - Bypass",
    "status": "active",
    "description": "12530 - Torque Cabeçote - Bypass",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "12530",
    "position": 12530
  },
  {
    "Characteristics": [],
    "thingId": 30,
    "code": "12600",
    "name": "12600 - Montagem e Registro dos Injetores / Trava dos Injetores",
    "status": "active",
    "description": "12600 - Montagem e Registro dos Injetores / Trava dos Injetores",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "12600",
    "position": 12600
  },
  {
    "Characteristics": [],
    "thingId": 31,
    "code": "12650",
    "name": "12650 - Torque Injetor",
    "status": "active",
    "description": "12650 - Torque Injetor",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "12650",
    "position": 12650
  },
  {
    "Characteristics": [],
    "thingId": 32,
    "code": "12700",
    "name": "12700 - Mtg Varetas / Balanceiros",
    "status": "active",
    "description": "12700 - Mtg Varetas / Balanceiros",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "12700",
    "position": 12700
  },
  {
    "Characteristics": [],
    "thingId": 33,
    "code": "12800",
    "name": "12800 - Torque Balanceiros / Porca Caneta / Sup Içto",
    "status": "active",
    "description": "12800 - Torque Balanceiros / Porca Caneta / Sup Içto",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "12800",
    "position": 12800
  },
  {
    "Characteristics": [],
    "thingId": 34,
    "code": "12905",
    "name": "12905 - Regulagem de Válvulas (Valve Lash) - Etapa 1",
    "status": "active",
    "description": "12905 - Regulagem de Válvulas (Valve Lash) - Etapa 1",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "12905",
    "position": 12905
  },
  {
    "Characteristics": [],
    "thingId": 35,
    "code": "13055",
    "name": "13055 - Regulagem de Válvulas (Valve Lash) - Etapa 2",
    "status": "active",
    "description": "13055 - Regulagem de Válvulas (Valve Lash) - Etapa 2",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "13055",
    "position": 13055
  },
  {
    "Characteristics": [],
    "thingId": 36,
    "code": "13070",
    "name": "13070 - Mesa Giratória",
    "status": "active",
    "description": "13070 - Mesa Giratória",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "13070",
    "position": 13070
  },
  {
    "Characteristics": [],
    "thingId": 37,
    "code": "13077",
    "name": "13077 - Retrabalho",
    "status": "active",
    "description": "13077 - Retrabalho",
    "parentThingId": 209,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "13077",
    "position": 13077
  },
  {
    "Characteristics": [],
    "thingId": 38,
    "code": "13100",
    "name": "13100 - Mtg Placa do Módulo / Bba Auxiliar",
    "status": "active",
    "description": "13100 - Mtg Placa do Módulo / Bba Auxiliar",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "13100",
    "position": 13100
  },
  {
    "Characteristics": [],
    "thingId": 39,
    "code": "13150",
    "name": "13150 - Mtg Aftercooler",
    "status": "active",
    "description": "13150 - Mtg Aftercooler",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "13150",
    "position": 13150
  },
  {
    "Characteristics": [],
    "thingId": 40,
    "code": "13200",
    "name": "13200 - Mtg Tub Alta Pressão / Torq Common Rail",
    "status": "active",
    "description": "13200 - Mtg Tub Alta Pressão / Torq Common Rail",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "13200",
    "position": 13200
  },
  {
    "Characteristics": [],
    "thingId": 41,
    "code": "13300",
    "name": "13300 - Torq Tub Alta Pressão",
    "status": "active",
    "description": "13300 - Torq Tub Alta Pressão",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "13300",
    "position": 13300
  },
  {
    "Characteristics": [],
    "thingId": 42,
    "code": "13455",
    "name": "13455 - Montagem da Tampa de Válvulas",
    "status": "active",
    "description": "13455 - Montagem da Tampa de Válvulas",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "13455",
    "position": 13455
  },
  {
    "Characteristics": [],
    "thingId": 43,
    "code": "13605",
    "name": "13605 - Coletor e Turbo",
    "status": "active",
    "description": "13605 - Coletor e Turbo",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "13605",
    "position": 13605
  },
  {
    "Characteristics": [],
    "thingId": 44,
    "code": "13655",
    "name": "13655 - Montagem Bi-Turbo",
    "status": "active",
    "description": "13655 - Montagem Bi-Turbo",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "13655",
    "position": 13655
  },
  {
    "Characteristics": [],
    "thingId": 45,
    "code": "13705",
    "name": "13705 - Conjunto Turbo e Coletor",
    "status": "active",
    "description": "13705 - Conjunto Turbo e Coletor",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "13705",
    "position": 13705
  },
  {
    "Characteristics": [],
    "thingId": 48,
    "code": "13955",
    "name": "13955 - Torque do Resfriador do Óleo / Torq Tubo Dreno",
    "status": "active",
    "description": "13955 - Torque do Resfriador do Óleo / Torq Tubo Dreno",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "13955",
    "position": 13955
  },
  {
    "Characteristics": [],
    "thingId": 49,
    "code": "14000",
    "name": "14000 - Tub de Baixa Pressão / Filtro de Comb",
    "status": "active",
    "description": "14000 - Tub de Baixa Pressão / Filtro de Comb",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "14000",
    "position": 14000
  },
  {
    "Characteristics": [],
    "thingId": 50,
    "code": "14055",
    "name": "14055 - Torque Âng Resfr Óleo / Bba Água / Conex Entr Água",
    "status": "active",
    "description": "14055 - Torque Âng Resfr Óleo / Bba Água / Conex Entr Água",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "14055",
    "position": 14055
  },
  {
    "Characteristics": [],
    "thingId": 51,
    "code": "14070",
    "name": "14070 - Tubo Ench Óleo / Mtg Módulo",
    "status": "active",
    "description": "14070 - Tubo Ench Óleo / Mtg Módulo",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "14070",
    "position": 14070
  },
  {
    "Characteristics": [],
    "thingId": 52,
    "code": "14105",
    "name": "14105 - Mtg Termostato",
    "status": "active",
    "description": "14105 - Mtg Termostato",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "14105",
    "position": 14105
  },
  {
    "Characteristics": [],
    "thingId": 54,
    "code": "14250",
    "name": "14250 - Mesa Giratória",
    "status": "active",
    "description": "14250 - Mesa Giratória",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "14250",
    "position": 14250
  },
  {
    "Characteristics": [],
    "thingId": 55,
    "code": "14260",
    "name": "14260 - Leak Test Água / Comb",
    "status": "active",
    "description": "14260 - Leak Test Água / Comb",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "14260",
    "position": 14260
  },
  {
    "Characteristics": [],
    "thingId": 56,
    "code": "14270",
    "name": "14270 - Leak Test Água / Comb",
    "status": "active",
    "description": "14270 - Leak Test Água / Comb",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "14270",
    "position": 14270
  },
  {
    "Characteristics": [],
    "thingId": 57,
    "code": "14277",
    "name": "14277 - Retrabalho",
    "status": "active",
    "description": "14277 - Retrabalho",
    "parentThingId": 209,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "14277",
    "position": 14277
  },
  {
    "Characteristics": [],
    "thingId": 58,
    "code": "14650",
    "name": "14650 - Mesa Giratória",
    "status": "active",
    "description": "14650 - Mesa Giratória",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "14650",
    "position": 14650
  },
  {
    "Characteristics": [],
    "thingId": 59,
    "code": "14670",
    "name": "14670 - Mtg e Torque Carcaça Volante",
    "status": "active",
    "description": "14670 - Mtg e Torque Carcaça Volante",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "14670",
    "position": 99999
  },
  {
    "Characteristics": [],
    "thingId": 60,
    "code": "14700",
    "name": "14700 - Mtg e Torque Carcaça Volante",
    "status": "active",
    "description": "14700 - Mtg e Torque Carcaça Volante",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "14700",
    "position": 99999
  },
  {
    "Characteristics": [],
    "thingId": 61,
    "code": "20610",
    "name": "20610 - Cel 6 - Mtg Pistão 1",
    "status": "active",
    "description": "20610 - Cel 6 - Mtg Pistão 1",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "20610",
    "position": 20610
  },
  {
    "Characteristics": [],
    "thingId": 62,
    "code": "20620",
    "name": "20620 - Cel 6 - Mtg Pistão 2",
    "status": "active",
    "description": "20620 - Cel 6 - Mtg Pistão 2",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "20620",
    "position": 20620
  },
  {
    "Characteristics": [],
    "thingId": 63,
    "code": "20630",
    "name": "20630 - Montagem do Pino do Pistão",
    "status": "active",
    "description": "20630 - Montagem do Pino do Pistão",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "20630",
    "position": 20630
  },
  {
    "Characteristics": [],
    "thingId": 64,
    "code": "20640",
    "name": "20640 - Sequenciamento",
    "status": "active",
    "description": "20640 - Sequenciamento",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "20640",
    "position": 20640
  },
  {
    "Characteristics": [],
    "thingId": 65,
    "code": "20710",
    "name": "20710 - Cel 7A - Mtg Cabeçote / Conectores / Tpa Adm",
    "status": "active",
    "description": "20710 - Cel 7A - Mtg Cabeçote / Conectores / Tpa Adm",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "20710",
    "position": 20710
  },
  {
    "Characteristics": [],
    "thingId": 66,
    "code": "20720",
    "name": "20720 - Cel 7B - Mtg Premtg Cab / Sup Içto / Conectores",
    "status": "active",
    "description": "20720 - Cel 7B - Mtg Premtg Cab / Sup Içto / Conectores",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "20720",
    "position": 20720
  },
  {
    "Characteristics": [],
    "thingId": 67,
    "code": "20910",
    "name": "20910 - Pré-Mtg Bba Comb",
    "status": "active",
    "description": "20910 - Pré-Mtg Bba Comb",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "20910",
    "position": 20910
  },
  {
    "Characteristics": [],
    "thingId": 69,
    "code": "30200",
    "name": "30200 - Mtg Freio Motor Fase 1",
    "status": "active",
    "description": "30200 - Mtg Freio Motor Fase 1",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "30200",
    "position": 0
  },
  {
    "Characteristics": [],
    "thingId": 70,
    "code": "30300",
    "name": "30300 - Mtg Freio Motor Fase 2",
    "status": "active",
    "description": "30300 - Mtg Freio Motor Fase 2",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "30300",
    "position": 30300
  },
  {
    "Characteristics": [],
    "thingId": 71,
    "code": "30400",
    "name": "30400 - Mtg Chicote / Crossover Aftercooler",
    "status": "active",
    "description": "30400 - Mtg Chicote / Crossover Aftercooler",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "30400",
    "position": 30400
  },
  {
    "Characteristics": [],
    "thingId": 72,
    "code": "30500",
    "name": "30500 - Preparação Tampa de Engrenagens",
    "status": "active",
    "description": "30500 - Preparação Tampa de Engrenagens",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "30500",
    "position": 30500
  },
  {
    "Characteristics": [],
    "thingId": 73,
    "code": "30600",
    "name": "30600 - Mtg / Torq Tpa Frontal",
    "status": "active",
    "description": "30600 - Mtg / Torq Tpa Frontal",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "30600",
    "position": 30600
  },
  {
    "Characteristics": [],
    "thingId": 74,
    "code": "30700",
    "name": "30700 - Mtg Pescador e Bad-Plate",
    "status": "active",
    "description": "30700 - Mtg Pescador e Bad-Plate",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "30700",
    "position": 30700
  },
  {
    "Characteristics": [],
    "thingId": 75,
    "code": "30800",
    "name": "30800 - Mtg do Carter",
    "status": "active",
    "description": "30800 - Mtg do Carter",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "30800",
    "position": 30800
  },
  {
    "Characteristics": [],
    "thingId": 76,
    "code": "30900",
    "name": "30900 - Torque do Carter",
    "status": "active",
    "description": "30900 - Torque do Carter",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "30900",
    "position": 30900
  },
  {
    "Characteristics": [],
    "thingId": 77,
    "code": "31000",
    "name": "31000 - Mtg Damper",
    "status": "active",
    "description": "31000 - Mtg Damper",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "31000",
    "position": 31000
  },
  {
    "Characteristics": [],
    "thingId": 78,
    "code": "31100",
    "name": "31100 - Mtg Cça de Volante",
    "status": "active",
    "description": "31100 - Mtg Cça de Volante",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "31100",
    "position": 31100
  },
  {
    "Characteristics": [],
    "thingId": 80,
    "code": "31400",
    "name": "31400 - Montagem",
    "status": "active",
    "description": "31400 - Montagem",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "31400",
    "position": 31400
  },
  {
    "Characteristics": [],
    "thingId": 81,
    "code": "31600",
    "name": "31600 - Leak Test Ar / Óleo",
    "status": "active",
    "description": "31600 - Leak Test Ar / Óleo",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "31600",
    "position": 31600
  },
  {
    "Characteristics": [],
    "thingId": 82,
    "code": "32100",
    "name": "32100 - Mtg do Volante",
    "status": "active",
    "description": "32100 - Mtg do Volante",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "32100",
    "position": 99999
  },
  {
    "Characteristics": [],
    "thingId": 84,
    "code": "31800",
    "name": "31800 - Enchimento de Óleo",
    "status": "active",
    "description": "31800 - Enchimento de Óleo",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "31800",
    "position": 31800
  },
  {
    "Characteristics": [],
    "thingId": 85,
    "code": "50300",
    "name": "50300 - Montagem Conexão de Escape",
    "status": "active",
    "description": "50300 - Montagem Conexão de Escape",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "50300",
    "position": 50300
  },
  {
    "Characteristics": [],
    "thingId": 86,
    "code": "50400",
    "name": "50400 - Montagem Polia Acessórios / Tensionador",
    "status": "active",
    "description": "50400 - Montagem Polia Acessórios / Tensionador",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "50400",
    "position": 50400
  },
  {
    "Characteristics": [],
    "thingId": 87,
    "code": "50500",
    "name": "50500 - Montagem Suporte Alternador",
    "status": "active",
    "description": "50500 - Montagem Suporte Alternador",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "50500",
    "position": 50500
  },
  {
    "Characteristics": [],
    "thingId": 88,
    "code": "50600",
    "name": "50600 - Montagem Flexplate / Torque Volante",
    "status": "active",
    "description": "50600 - Montagem Flexplate / Torque Volante",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "50600",
    "position": 50600
  },
  {
    "Characteristics": [],
    "thingId": 90,
    "code": "50700",
    "name": "50700 - Montagem Suporte Traseiro",
    "status": "active",
    "description": "50700 - Montagem Suporte Traseiro",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "50700",
    "position": 50700
  },
  {
    "Characteristics": [],
    "thingId": 92,
    "code": "51800",
    "name": "51800 - Tubo Respiro / Alternador / Costumer Label",
    "status": "active",
    "description": "51800 - Tubo Respiro / Alternador / Costumer Label",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "51800",
    "position": 51800
  },
  {
    "Characteristics": [],
    "thingId": 93,
    "code": "ISF 2.8",
    "name": "ISF 2.8",
    "status": "active",
    "description": "ISF 2.8",
    "parentThingId": 207,
    "thingLvlDescription": "Área",
    "thingLvl": 2,
    "thingType": null,
    "physicalConn": "ISF 2.8",
    "position": 1
  },
  {
    "Characteristics": [],
    "thingId": 94,
    "code": "60100",
    "name": "60100 - Lineset",
    "status": "active",
    "description": "60100 - Lineset",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "60100",
    "position": 0
  },
  {
    "Characteristics": [],
    "thingId": 95,
    "code": "60200",
    "name": "60200 - Gravação do Número de Série",
    "status": "active",
    "description": "60200 - Gravação do Número de Série",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "60200",
    "position": 60200
  },
  {
    "Characteristics": [],
    "thingId": 97,
    "code": "60400",
    "name": "60400 - Soltar Capas de Mancal Bloco / Bronzina da Capa",
    "status": "active",
    "description": "60400 - Soltar Capas de Mancal Bloco / Bronzina da Capa",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "60400",
    "position": 60400
  },
  {
    "Characteristics": [],
    "thingId": 98,
    "code": "60500",
    "name": "60500 - Montagem Virabrequim / Bico Resfriador / Bronzina Bloco / Oleamento",
    "status": "active",
    "description": "60500 - Montagem Virabrequim / Bico Resfriador / Bronzina Bloco / Oleamento",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "60500",
    "position": 60500
  },
  {
    "Characteristics": [],
    "thingId": 99,
    "code": "60600",
    "name": "60600 - Torque dos Mancais",
    "status": "active",
    "description": "60600 - Torque dos Mancais",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "60600",
    "position": 60600
  },
  {
    "Characteristics": [],
    "thingId": 100,
    "code": "60610",
    "name": "60610 - Retrabalho Mancal",
    "status": "active",
    "description": "60610 - Retrabalho Mancal",
    "parentThingId": 209,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "60610",
    "position": 60610
  },
  {
    "Characteristics": [],
    "thingId": 101,
    "code": "60700",
    "name": "60700 - Tombador / Torque de Giro",
    "status": "active",
    "description": "60700 - Tombador / Torque de Giro",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "60700",
    "position": 60700
  },
  {
    "Characteristics": [],
    "thingId": 102,
    "code": "60800",
    "name": "60800 - Montagem dos Pistões",
    "status": "active",
    "description": "60800 - Montagem dos Pistões",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "60800",
    "position": 60800
  },
  {
    "Characteristics": [],
    "thingId": 103,
    "code": "60801",
    "name": "60801 - Pré-Montagem Aneis dos Pistões",
    "status": "active",
    "description": "60801 - Pré-Montagem Aneis dos Pistões",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "60801",
    "position": 60801
  },
  {
    "Characteristics": [],
    "thingId": 104,
    "code": "60802",
    "name": "60802 - Pré-Montagem Conjunto Pistão / Biela",
    "status": "active",
    "description": "60802 - Pré-Montagem Conjunto Pistão / Biela",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "60802",
    "position": 60802
  },
  {
    "Characteristics": [],
    "thingId": 105,
    "code": "60803",
    "name": "60803 - Pré-Montagem Pistão 3",
    "status": "active",
    "description": "60803 - Pré-Montagem Pistão 3",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "60803",
    "position": 60803
  },
  {
    "Characteristics": [],
    "thingId": 106,
    "code": "60805",
    "name": "60805 - Torque da Biela",
    "status": "active",
    "description": "60805 - Torque da Biela",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "60805",
    "position": 60805
  },
  {
    "Characteristics": [],
    "thingId": 107,
    "code": "61000",
    "name": "61000 - Protrusão / Torque de Giro",
    "status": "active",
    "description": "61000 - Protrusão / Torque de Giro",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "61000",
    "position": 61000
  },
  {
    "Characteristics": [],
    "thingId": 108,
    "code": "61100",
    "name": "61100 - Posicionamento do Cabeçote",
    "status": "active",
    "description": "61100 - Posicionamento do Cabeçote",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "61100",
    "position": 61100
  },
  {
    "Characteristics": [],
    "thingId": 109,
    "code": "61200",
    "name": "61200 - Torque do Cabeçote",
    "status": "active",
    "description": "61200 - Torque do Cabeçote",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "61200",
    "position": 61200
  },
  {
    "Characteristics": [],
    "thingId": 110,
    "code": "61210",
    "name": "61210 - Retrabalho Cabeçote",
    "status": "active",
    "description": "61210 - Retrabalho Cabeçote",
    "parentThingId": 209,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "61210",
    "position": 61210
  },
  {
    "Characteristics": [],
    "thingId": 111,
    "code": "61300",
    "name": "61300 - Montagem do Eixo Comando e Tampa Frontal",
    "status": "active",
    "description": "61300 - Montagem do Eixo Comando e Tampa Frontal",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "61300",
    "position": 61300
  },
  {
    "Characteristics": [],
    "thingId": 112,
    "code": "61400",
    "name": "61400 - Montagem Corrente de Transmissão",
    "status": "active",
    "description": "61400 - Montagem Corrente de Transmissão",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "61400",
    "position": 61400
  },
  {
    "Characteristics": [],
    "thingId": 113,
    "code": "61500",
    "name": "61500 - Montagem e Torque da Carcaça de Volante",
    "status": "active",
    "description": "61500 - Montagem e Torque da Carcaça de Volante",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "61500",
    "position": 61500
  },
  {
    "Characteristics": [],
    "thingId": 114,
    "code": "61600",
    "name": "61600 - Montagem do Coletor de Admissão",
    "status": "active",
    "description": "61600 - Montagem do Coletor de Admissão",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "61600",
    "position": 61600
  },
  {
    "Characteristics": [],
    "thingId": 115,
    "code": "61700",
    "name": "61700 - Montagem do Tensionador e Bomba de Combustível",
    "status": "active",
    "description": "61700 - Montagem do Tensionador e Bomba de Combustível",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "61700",
    "position": 61700
  },
  {
    "Characteristics": [],
    "thingId": 116,
    "code": "61800",
    "name": "61800 - Montagem e Torque do Carter",
    "status": "active",
    "description": "61800 - Montagem e Torque do Carter",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "61800",
    "position": 61800
  },
  {
    "Characteristics": [],
    "thingId": 117,
    "code": "61900",
    "name": "61900 - Montagem dos Balanceiros / Prensa dos Retentores",
    "status": "active",
    "description": "61900 - Montagem dos Balanceiros / Prensa dos Retentores",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "61900",
    "position": 61900
  },
  {
    "Characteristics": [],
    "thingId": 118,
    "code": "62000",
    "name": "62000 - Valve Lash",
    "status": "active",
    "description": "62000 - Valve Lash",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "62000",
    "position": 62000
  },
  {
    "Characteristics": [],
    "thingId": 119,
    "code": "62100",
    "name": "62100 - Montagem da Tampa de Válvulas",
    "status": "active",
    "description": "62100 - Montagem da Tampa de Válvulas",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "62100",
    "position": 62100
  },
  {
    "Characteristics": [],
    "thingId": 120,
    "code": "62200",
    "name": "62200 - Montagem do Sistema de Combustível + Injetor",
    "status": "active",
    "description": "62200 - Montagem do Sistema de Combustível + Injetor",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "62200",
    "position": 62200
  },
  {
    "Characteristics": [],
    "thingId": 121,
    "code": "62210",
    "name": "62210 - Retrabalho",
    "status": "active",
    "description": "62210 - Retrabalho",
    "parentThingId": 209,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "62210",
    "position": 62210
  },
  {
    "Characteristics": [],
    "thingId": 122,
    "code": "62300",
    "name": "62300 - Montagem do Coletor de Escape (Turbo)",
    "status": "active",
    "description": "62300 - Montagem do Coletor de Escape (Turbo)",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "62300",
    "position": 62300
  },
  {
    "Characteristics": [],
    "thingId": 123,
    "code": "62400",
    "name": "62400 - Montagem das Tubulações de Alta Pressão",
    "status": "active",
    "description": "62400 - Montagem das Tubulações de Alta Pressão",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "62500",
    "position": 62500
  },
  {
    "Characteristics": [],
    "thingId": 124,
    "code": "62500",
    "name": "62500 - Montagem da Carcaça Termostática e Sensores",
    "status": "active",
    "description": "62500 - Montagem da Carcaça Termostática e Sensores",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "62500",
    "position": 62500
  },
  {
    "Characteristics": [],
    "thingId": 125,
    "code": "62600",
    "name": "62600 - Montagem do Chicote Elétrico",
    "status": "active",
    "description": "62600 - Montagem do Chicote Elétrico",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "62600",
    "position": 62600
  },
  {
    "Characteristics": [],
    "thingId": 126,
    "code": "62700",
    "name": "62700 - Leak Test 1",
    "status": "active",
    "description": "62700 - Leak Test 1",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "62700",
    "position": 99998
  },
  {
    "Characteristics": [],
    "thingId": 127,
    "code": "62800",
    "name": "62800 - Leak Test 2",
    "status": "active",
    "description": "62800 - Leak Test 2",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "62800",
    "position": 99998
  },
  {
    "Characteristics": [],
    "thingId": 128,
    "code": "62900",
    "name": "62900 - Montagem do Volante",
    "status": "active",
    "description": "62900 - Montagem do Volante",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "62900",
    "position": 62900
  },
  {
    "Characteristics": [],
    "thingId": 129,
    "code": "63000",
    "name": "63000 - Audit Station + Quality Gate",
    "status": "active",
    "description": "63000 - Audit Station + Quality Gate",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "63000",
    "position": 63000
  },
  {
    "Characteristics": [],
    "thingId": 130,
    "code": "63100",
    "name": "63100 - Enchimento de Óleo",
    "status": "active",
    "description": "63100 - Enchimento de Óleo",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "63100",
    "position": 99999
  },
  {
    "Characteristics": [],
    "thingId": 135,
    "code": "10100",
    "name": "10100 - Lineset",
    "status": "active",
    "description": "10100 - Lineset",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "10100",
    "position": 0
  },
  {
    "Characteristics": [
      {
        "characteristicId": 57,
        "value": "1234567890",
        "key": "Data Takt Time",
        "Thing_thingId": 149
      },
      {
        "characteristicId": 58,
        "value": "25",
        "key": "Tempo de ATR",
        "Thing_thingId": 149
      },
      {
        "characteristicId": 59,
        "value": "25",
        "key": "Takt Time",
        "Thing_thingId": 149
      }
    ],
    "thingId": 149,
    "code": "11000",
    "name": "11000 - Prensagem Camisas",
    "status": "active",
    "description": "11000 - Prensagem Camisas",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "11000",
    "position": 11000
  },
  {
    "Characteristics": [],
    "thingId": 150,
    "code": "PGTO",
    "name": "PAGAMENTO",
    "status": "active",
    "description": "PAGAMENTO",
    "parentThingId": 207,
    "thingLvlDescription": "Área",
    "thingLvl": 2,
    "thingType": null,
    "physicalConn": "PAGAMENTO",
    "position": 0
  },
  {
    "Characteristics": [],
    "thingId": 152,
    "code": "32000",
    "name": "32000 - Teste de Integridade",
    "status": "active",
    "description": "32000 - Teste de Integridade",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "32000",
    "position": 32000
  },
  {
    "Characteristics": [],
    "thingId": 153,
    "code": "31300",
    "name": "31300 - Mtg Tub Compressor / Tubo de Vareta",
    "status": "active",
    "description": "31300 - Mtg Tub Compressor / Tubo de Vareta",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "31300",
    "position": 31300
  },
  {
    "Characteristics": [],
    "thingId": 155,
    "code": "50200",
    "name": "50200 - Montagem Suporte Frontal",
    "status": "active",
    "description": "50200 - Montagem Suporte Frontal",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "50200",
    "position": 50200
  },
  {
    "Characteristics": [],
    "thingId": 156,
    "code": "70100",
    "name": "70100 - Lineset Non-Engine",
    "status": "active",
    "description": "70100 - Lineset Non-Engine",
    "parentThingId": 210,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "70100",
    "position": 70100
  },
  {
    "Characteristics": [],
    "thingId": 157,
    "code": "10200",
    "name": "10200 - Gravação ESN",
    "status": "active",
    "description": "10200 - Gravação ESN",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "10200",
    "position": 10200
  },
  {
    "Characteristics": [],
    "thingId": 158,
    "code": "51500",
    "name": "51500 - Empapelamento",
    "status": "active",
    "description": "51500 - Empapelamento (SEM PLC)",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "51500",
    "position": 51500
  },
  {
    "Characteristics": [],
    "thingId": 159,
    "code": "10250",
    "name": "10250 - Mesa Giratória",
    "status": "active",
    "description": "10250 - Mesa Giratória",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "10250",
    "position": 10250
  },
  {
    "Characteristics": [],
    "thingId": 160,
    "code": "11100",
    "name": "11100 - Eixo Comando / Cça Eng",
    "status": "active",
    "description": "11100 - Eixo Comando / Cça Eng",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "11100",
    "position": 11100
  },
  {
    "Characteristics": [],
    "thingId": 161,
    "code": "11200",
    "name": "11200 - Cça Eng / Bba Óleo",
    "status": "active",
    "description": "11200 - Cça Eng / Bba Óleo",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "11200",
    "position": 11200
  },
  {
    "Characteristics": [],
    "thingId": 165,
    "code": "20700",
    "name": "20700 - Cel 7 - Entrada Cabeçote",
    "status": "active",
    "description": "20700 - Cel 7 - Entrada Cabeçote",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "20700",
    "position": 20700
  },
  {
    "Characteristics": [],
    "thingId": 166,
    "code": "51600",
    "name": "51600 - Robô de Pintura",
    "status": "active",
    "description": "51600 - Robô de Pintura",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "51600",
    "position": 99999
  },
  {
    "Characteristics": [],
    "thingId": 168,
    "code": "51200",
    "name": "51200 - Transferência Aéreo",
    "status": "active",
    "description": "51200 - Transferência Aéreo (SEM PLC)",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "51200",
    "position": 0
  },
  {
    "Characteristics": [],
    "thingId": 169,
    "code": "10120",
    "name": "10120 - Picking Light Direito",
    "status": "active",
    "description": "10120 - Picking Light Direito",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "10120",
    "position": 10120
  },
  {
    "Characteristics": [],
    "thingId": 170,
    "code": "10455",
    "name": "10455 - Mtg Tucho / Bico Resfriador / Bronzina Bloco",
    "status": "active",
    "description": "10455 - Mtg Tucho / Bico Resfriador / Bronzina Bloco",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "10455",
    "position": 10455
  },
  {
    "Characteristics": [],
    "thingId": 171,
    "code": "11720",
    "name": "11720 - Setup Pallet",
    "status": "active",
    "description": "11720 - Setup Pallet",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "11720",
    "position": 11720
  },
  {
    "Characteristics": [],
    "thingId": 172,
    "code": "13105",
    "name": "13105 - Montagem Resfriador",
    "status": "active",
    "description": "13105 - Montagem Resfriador",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "13105",
    "position": 13105
  },
  {
    "Characteristics": [],
    "thingId": 173,
    "code": "20100",
    "name": "20100 - Cel 1 - Mtg do Módulo",
    "status": "active",
    "description": "20100 - Cel 1 - Mtg do Módulo",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "20100",
    "position": 20100
  },
  {
    "Characteristics": [],
    "thingId": 175,
    "code": "20200",
    "name": "20200 - Cel 2 - Conex Tub Comb",
    "status": "active",
    "description": "20200 - Cel 2 - Conex Tub Comb",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "20200",
    "position": 20200
  },
  {
    "Characteristics": [],
    "thingId": 176,
    "code": "20300",
    "name": "20300 - Cel 3 - Conex / Cubo Vent / Alternador",
    "status": "active",
    "description": "20300 - Cel 3 - Conex / Cubo Vent / Alternador",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "20300",
    "position": 20300
  },
  {
    "Characteristics": [],
    "thingId": 177,
    "code": "20400",
    "name": "20400 - Cel 4 - Mtg Virabrequim / Comando",
    "status": "active",
    "description": "20400 - Cel 4 - Mtg Virabrequim / Comando",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "20400",
    "position": 20400
  },
  {
    "Characteristics": [],
    "thingId": 178,
    "code": "20800",
    "name": "20800 - Cel 8 - Mtg Cça Repto / Tpa Tras / Tpa Engren",
    "status": "active",
    "description": "20800 - Cel 8 - Mtg Cça Repto / Tpa Tras / Tpa Engren",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "20800",
    "position": 20800
  },
  {
    "Characteristics": [],
    "thingId": 179,
    "code": "20920",
    "name": "20920 - Pré-Mtg Compressor Ar",
    "status": "active",
    "description": "20920 - Pré-Mtg Compressor Ar",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "20920",
    "position": 20920
  },
  {
    "Characteristics": [],
    "thingId": 180,
    "code": "21200",
    "name": "21200 - Cel 12 - Mtg Coletor Escape / Turbo Baixo",
    "status": "active",
    "description": "21200 - Cel 12 - Mtg Coletor Escape / Turbo Baixo",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "21200",
    "position": 21200
  },
  {
    "Characteristics": [],
    "thingId": 181,
    "code": "21210",
    "name": "21210 - Cel 13 - Mtg Turbo ISF",
    "status": "active",
    "description": "21210 - Cel 13 - Mtg Turbo ISF",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "21210",
    "position": 21210
  },
  {
    "Characteristics": [],
    "thingId": 182,
    "code": "21100",
    "name": "21100 - Cel 11 - Mtg Resfr Óleo",
    "status": "active",
    "description": "21100 - Cel 11 - Mtg Resfr Óleo",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "21100",
    "position": 21100
  },
  {
    "Characteristics": [],
    "thingId": 183,
    "code": "14500",
    "name": "14500 - Quality Gate",
    "status": "active",
    "description": "14500 - Quality Gate (SEM PLC)",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "14500",
    "position": 14500
  },
  {
    "Characteristics": [],
    "thingId": 184,
    "code": "14505",
    "name": "14505 - Quality Gate",
    "status": "active",
    "description": "14505 - Quality Gate (SEM PLC)",
    "parentThingId": 2,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "14505",
    "position": 14505
  },
  {
    "Characteristics": [],
    "thingId": 185,
    "code": "20110",
    "name": "20110 - Manta",
    "status": "active",
    "description": "20110 - Manta",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "20110",
    "position": 20110
  },
  {
    "Characteristics": [],
    "thingId": 186,
    "code": "21000",
    "name": "21000 - Cel 10 - Mtg Tpa Válvulas / Cça Balanceiros",
    "status": "active",
    "description": "21000 - Cel 10 - Mtg Tpa Válvulas / Cça Balanceiros",
    "parentThingId": 211,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "21000",
    "position": 21000
  },
  {
    "Characteristics": [],
    "thingId": 187,
    "code": "62750",
    "name": "62750 - Leak Test / ETS",
    "status": "active",
    "description": "62750 - Leak Test / ETS (SEM PLC)",
    "parentThingId": 93,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "62750",
    "position": 62750
  },
  {
    "Characteristics": [],
    "thingId": 188,
    "code": "31700",
    "name": "31700 - Audit Station",
    "status": "active",
    "description": "31700 - Audit Station (SEM PLC)",
    "parentThingId": 3,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "31700",
    "position": 31700
  },
  {
    "Characteristics": [],
    "thingId": 189,
    "code": "40511",
    "name": "40511 - Sala Teste 11 MEC",
    "status": "active",
    "description": "40511 - Sala Teste 11 MEC (SEM PLC)",
    "parentThingId": 208,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "40511",
    "position": 99999
  },
  {
    "Characteristics": [],
    "thingId": 190,
    "code": "40512",
    "name": "40512 - Sala Teste 12 MEC",
    "status": "active",
    "description": "40512 - Sala Teste 12 MEC (SEM PLC)",
    "parentThingId": 208,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "40512",
    "position": 99999
  },
  {
    "Characteristics": [],
    "thingId": 191,
    "code": "40513",
    "name": "40513 - Sala Teste 13 MEC",
    "status": "active",
    "description": "40513 - Sala Teste 13 MEC (SEM PLC)",
    "parentThingId": 208,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "40513",
    "position": 99999
  },
  {
    "Characteristics": [],
    "thingId": 192,
    "code": "40608",
    "name": "40608 - Salta Teste 08 Sytech",
    "status": "active",
    "description": "40608 - Salta Teste 08 Sytech (SEM PLC)",
    "parentThingId": 208,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "40608",
    "position": 99999
  },
  {
    "Characteristics": [],
    "thingId": 193,
    "code": "40609",
    "name": "40609 - Salta Teste 09 Sytech",
    "status": "active",
    "description": "40609 - Salta Teste 09 Sytech (SEM PLC)",
    "parentThingId": 208,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "40609",
    "position": 99999
  },
  {
    "Characteristics": [],
    "thingId": 194,
    "code": "40610",
    "name": "40610 - Salta Teste 10 Sytech",
    "status": "active",
    "description": "40610 - Salta Teste 10 Sytech (SEM PLC)",
    "parentThingId": 208,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "40610",
    "position": 99999
  },
  {
    "Characteristics": [],
    "thingId": 195,
    "code": "40100",
    "name": "40100 - Leak Test KDB",
    "status": "active",
    "description": "40100 - Leak Test KDB",
    "parentThingId": 208,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "40100",
    "position": 1
  },
  {
    "Characteristics": [],
    "thingId": 196,
    "code": "40330",
    "name": "40330 - Leak Test Comb / Água Retrabalho",
    "status": "active",
    "description": "40330 - Leak Test Comb / Água Retrabalho",
    "parentThingId": 208,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "40330",
    "position": 1
  },
  {
    "Characteristics": [],
    "thingId": 197,
    "code": "52000",
    "name": "52000 - Logotipo / Etiquetas",
    "status": "active",
    "description": "52000 - Logotipo / Etiquetas (SEM PLC)",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "52000",
    "position": 52000
  },
  {
    "Characteristics": [],
    "thingId": 198,
    "code": "52100",
    "name": "52100 - Plaqueta de Dados Motor",
    "status": "active",
    "description": "52100 - Plaqueta de Dados Motor (SEM PLC)",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "52100",
    "position": 52100
  },
  {
    "Characteristics": [],
    "thingId": 199,
    "code": "52300",
    "name": "52300 - Montagem Kit - 01",
    "status": "active",
    "description": "52300 - Montagem Kit - 01 (SEM PLC)",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "52300",
    "position": 52300
  },
  {
    "Characteristics": [],
    "thingId": 200,
    "code": "52500",
    "name": "52500 - Inspeção Aéreo",
    "status": "active",
    "description": "52500 - Inspeção Aéreo (SEM PLC)",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "52500",
    "position": 52500
  },
  {
    "Characteristics": [],
    "thingId": 201,
    "code": "52600",
    "name": "52600 - Inspeção Aéreo",
    "status": "active",
    "description": "52600 - Inspeção Aéreo (SEM PLC)",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "52600",
    "position": 52600
  },
  {
    "Characteristics": [],
    "thingId": 202,
    "code": "52700",
    "name": "52700 - Inspeção Aéreo",
    "status": "active",
    "description": "52700 - Inspeção Aéreo (SEM PLC)",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "52700",
    "position": 52700
  },
  {
    "Characteristics": [],
    "thingId": 203,
    "code": "52800",
    "name": "52800 - Inspeção Aéreo",
    "status": "active",
    "description": "52800 - Inspeção Aéreo (SEM PLC)",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "52800",
    "position": 52800
  },
  {
    "Characteristics": [],
    "thingId": 204,
    "code": "52900",
    "name": "52900 - Bxa Kit / Transferência Skid Motor",
    "status": "active",
    "description": "52900 - Bxa Kit / Transferência Skid Motor (SEM PLC)",
    "parentThingId": 4,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "52900",
    "position": 99998
  },
  {
    "Characteristics": [],
    "thingId": 205,
    "code": "53100",
    "name": "53100 - Inspeção Pátio / Pagamento",
    "status": "active",
    "description": "53100 - Inspeção Pátio / Pagamento (SEM PLC)",
    "parentThingId": 150,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "53100",
    "position": 99999
  },
  {
    "Characteristics": [],
    "thingId": 206,
    "code": "53105",
    "name": "53105 - Inspeção Pátio / Pagamento 2",
    "status": "active",
    "description": "53105 - Inspeção Pátio / Pagamento 2 (SEM PLC)",
    "parentThingId": 150,
    "thingLvlDescription": "Estágio",
    "thingLvl": 1,
    "thingType": null,
    "physicalConn": "53105",
    "position": 99999
  },
  {
    "Characteristics": [],
    "thingId": 207,
    "code": "Linha",
    "name": "Linha de Montagem de Motores",
    "status": "active",
    "description": "Linha de Montagem de Motores",
    "parentThingId": 0,
    "thingLvlDescription": "Linha",
    "thingLvl": 3,
    "thingType": null,
    "physicalConn": null,
    "position": 1
  },
  {
    "Characteristics": [],
    "thingId": 208,
    "code": "TESTE",
    "name": "TESTE",
    "status": "active",
    "description": "TESTE",
    "parentThingId": 207,
    "thingLvlDescription": "Área",
    "thingLvl": 2,
    "thingType": null,
    "physicalConn": "TESTE",
    "position": 2
  },
  {
    "Characteristics": [],
    "thingId": 209,
    "code": "RETRABALHO",
    "name": "RETRABALHO",
    "status": "active",
    "description": "RETRABALHO",
    "parentThingId": 207,
    "thingLvlDescription": "Área",
    "thingLvl": 2,
    "thingType": null,
    "physicalConn": "RETRABALHO",
    "position": 2
  },
  {
    "Characteristics": [],
    "thingId": 210,
    "code": "NON-ENGINE",
    "name": "NON-ENGINE",
    "status": "active",
    "description": "NON-ENGINE",
    "parentThingId": 207,
    "thingLvlDescription": "Área",
    "thingLvl": 2,
    "thingType": null,
    "physicalConn": "NON-ENGINE",
    "position": 2
  },
  {
    "Characteristics": [],
    "thingId": 211,
    "code": "PRÉ-MONTAGEM",
    "name": "PRÉ-MONTAGEM",
    "status": "active",
    "description": "PRÉ-MONTAGEM",
    "parentThingId": 207,
    "thingLvlDescription": "Área",
    "thingLvl": 2,
    "thingType": null,
    "physicalConn": "PRÉ-MONTAGEM",
    "position": 1
  }
];
var http = require('http');

default_states = [
{
	"status":"OFFLINE",
	"color":"#AAAAAA",
	"fontColor":"#000000",
},{
	"status":"ESN",
	"color":"#00FF00",
	"fontColor":"#000000",
},{
	"status":"EMPTY",
	"color":"#0000FF",
	"fontColor":"#FFFFFF",
},{
	"status":"PECA_FALTANTE",
	"color":"#E47833",
	"fontColor":"#000000",
},{
	"status":"EM_MANUAL",
	"color":"#000000",
	"fontColor":"#AAAAAA",
},{
	"status":"EM_ALARME",
	"color":"#FFFFFF",
	"fontColor":"#AAAAAA",
}]

for(var i=0;i<=things;i++){
	
}